{
 "title": "Realraum",
 "description": "A dashboard to monitor the realraum hackerspace",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "door_contact",
    "label": "Türkontakt",
    "query": "SELECT\n  description\nFROM\n(\nSELECT\n    arrayJoin(argMax(door_contact, timestamp)) as doors,\n    JSONExtractString(doors, 'description') as description,\n    JSONExtractBool(doors, 'value') as value\nFROM stats\n)\nGROUP BY description"
   },
   {
    "name": "door_locked",
    "label": "Türschloss",
    "query": "SELECT\n  description\nFROM\n(\nSELECT\n    arrayJoin(argMax(door_locked, timestamp)) as doors,\n    JSONExtractString(doors, 'description') as description,\n    JSONExtractBool(doors, 'value') as value\nFROM stats\n)\nGROUP BY description"
   },
   {
    "name": "temperature_sensors",
    "query": "SELECT\n  arrayJoin(arrayMap(x -> JSONExtractString(x, 'name'), any(temperature))) as names\nFROM stats"
   },
   { "name": "ds", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Members" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n  timestamp as t,\n  any(total_member_count) as `Members`\nFROM\n  stats\nWHERE\n  $__timeFilter(t)\nGROUP BY\n  t\nORDER BY\n  t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "realraum Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    timestamp as t,\n    any(state_open) as `State`\nFROM stats\n\nWHERE $__timeFilter(t)\n\nGROUP BY t\n\nORDER BY t\n",
     "round": "0s"
    }
   ]
  },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH\n  JSONExtractRaw(any(json), 'state') as state,\n  JSONExtractRaw(state, 'icon') as icon\nSELECT\n  JSONExtractBool(state, 'open') ? JSONExtractString(icon, 'open') : JSONExtractString(icon, 'closed') as url,\n  timestamp as t\nFROM\n  stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t desc\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    timestamp as t,\n    toUInt64(any(state_lastchange)) * 1000 as `Last Change` -- grafana and everything is shit (timezones)\nFROM stats\n\nWHERE $__timeFilter(t)\n\nGROUP BY t\n\nORDER BY t\n",
     "round": "0s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    timestamp as t,\n    any(JSONExtractString(json, 'message')) as `Message`\nFROM stats\n\nWHERE $__timeFilter(t)\n\nGROUP BY t\n\nORDER BY t\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Door Contacts",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n  t,\n  description,\n  any(value) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayJoin(any(door_contact)) as doors,\n    JSONExtractString(doors, 'description') as description,\n    JSONExtractBool(doors, 'value') as value\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, description\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Door Locks",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n  t,\n  description,\n  any(value) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayJoin(any(door_locked)) as doors,\n    JSONExtractString(doors, 'description') as description,\n    JSONExtractBool(doors, 'value') as value\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, description\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  { "title": "Environment Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$temperature_sensors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "repeat": "temperature_sensors",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    t,\n    (arrayJoin(arrayZip(names, values)) as x).1 as name,\n    any(x.2) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayMap(x -> JSONExtractString(x, 'name'), any(temperature)) as names,\n    arrayMap(x -> JSONExtractFloat(x, 'value'), any(temperature)) as values,\n    arrayMap(x -> JSONExtractString(x, 'timestamp'), any(temperature)) as timestamps,\n    arrayMap(x -> JSONExtractString(x, 'unit'), any(temperature)) as untis\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nWHERE name = '$temperature_sensors'\nGROUP BY t, name\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    t,\n    (arrayJoin(arrayZip(names, values)) as x).1 as name,\n    any(x.2) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayMap(x -> JSONExtractString(x, 'name'), any(temperature)) as names,\n    arrayMap(x -> JSONExtractFloat(x, 'value'), any(temperature)) as values,\n    arrayMap(x -> JSONExtractString(x, 'timestamp'), any(temperature)) as timestamps,\n    arrayMap(x -> JSONExtractString(x, 'unit'), any(temperature)) as untis\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, name\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    t,\n    (arrayJoin(arrayZip(names, values)) as x).1 as name,\n    any(x.2) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayMap(x -> JSONExtractString(x, 'name'), any(humidity)) as names,\n    arrayMap(x -> JSONExtractFloat(x, 'value'), any(humidity)) as values,\n    arrayMap(x -> JSONExtractString(x, 'timestamp'), any(humidity)) as timestamps,\n    arrayMap(x -> JSONExtractString(x, 'unit'), any(humidity)) as untis\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, name\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    t,\n    (arrayJoin(arrayZip(names, values)) as x).1 as name,\n    any(x.2) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayMap(x -> JSONExtractString(x, 'name'), any(voltage)) as names,\n    arrayMap(x -> JSONExtractFloat(x, 'value'), any(voltage)) as values,\n    arrayMap(x -> JSONExtractString(x, 'timestamp'), any(voltage)) as timestamps,\n    arrayMap(x -> JSONExtractString(x, 'unit'), any(voltage)) as untis\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, name\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Barometer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    t,\n    (arrayJoin(arrayZip(names, values)) as x).1 as name,\n    any(x.2) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayMap(x -> JSONExtractString(x, 'name'), any(barometer)) as names,\n    arrayMap(x -> JSONExtractFloat(x, 'value'), any(barometer)) as values,\n    arrayMap(x -> JSONExtractString(x, 'timestamp'), any(barometer)) as timestamps,\n    arrayMap(x -> JSONExtractString(x, 'unit'), any(barometer)) as untis\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, name\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Illumination",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "database": "realraum",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "rawSql": "SELECT\n    t,\n    (arrayJoin(arrayZip(names, values)) as x).1 as name,\n    any(x.2) as Value\nFROM\n(\nSELECT\n    timestamp as t,\n    arrayMap(x -> JSONExtractString(x, 'name'), any(illumination)) as names,\n    arrayMap(x -> JSONExtractFloat(x, 'value'), any(illumination)) as values,\n    arrayMap(x -> JSONExtractString(x, 'timestamp'), any(illumination)) as timestamps,\n    arrayMap(x -> JSONExtractString(x, 'unit'), any(illumination)) as untis\nFROM stats\nWHERE $__timeFilter(t)\nGROUP BY t\nORDER BY t\n)\nGROUP BY t, name\nORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}